### ISSUE TITLE
Fix build after merge of whitelisting current active to change SSID to MamaConnect

### ISSUE THREAD

**Issue by Johanndutoit** [praekeltfoundation/goddard-captive-portal#2]
Get tests building again

**Comment by skibz** [comment]
@Johanndutoit 

it looks like the assertions just need to be changed on these lines:

https://github.com/praekelt/goddard-captive-portal/blob/develop/test/index.js#L100
https://github.com/praekelt/goddard-captive-portal/blob/develop/test/index.js#L105
https://github.com/praekelt/goddard-captive-portal/blob/develop/test/index.js#L111
https://github.com/praekelt/goddard-captive-portal/blob/develop/test/index.js#L129

the code you added causes the web server to send a 302 status code, but the tests are asserting that the status code is 200. 
:+1: :+1:

**Comment by Johanndutoit** [comment]
@skibz thanks for checking :)

Yes forgot that we are now redirecting to mamawifi.com if it's not detected. Will smart it up a bit.
